#!/bin/bash

CHEF_SERVER=$1
CHEF_ROLE=$2

# let's get Ubuntu up to date and install the Chef gem
apt-get update
apt-get upgrade
apt-get install ruby ruby-dev libopenssl-ruby rdoc ri irb build-essential wget ssl-cert openssh-server
cd /tmp
wget http://production.cf.rubygems.org/rubygems/rubygems-1.3.7.tgz
tar zxf rubygems-1.3.7.tgz
cd rubygems-1.3.7
ruby setup.rb
ln -sfv /usr/bin/gem1.8 /usr/bin/gem
gem install chef --no-rdoc --no-ri

# download chef scripts and configuration files
# note that CHEF_ROLE dictates with JSON file to use (associates client with that role)
mkdir -p /etc/chef
wget -qO/etc/chef/client.rb http://github.com/ijonas/my-chef-scripts/raw/master/client.rb
# wget -qO/etc/chef/chef.json http://github.com/ijonas/my-chef-scripts/raw/master/chef.${CHEF_ROLE}.json
wget -qO/etc/init.d/chef-client http://gist.github.com/raw/484780/ac3753ed0f75631e56b638c5ee343967a555edf2/gistfile1.txt
scp root@${CHEF_SERVER}:/etc/chef/validation.pem /etc/chef/validation.pem

# initial run of chef -- role association happens
chef-client -L /var/log/chef.log -l debug

# remove validation key
rm -rf /etc/chef/validation.pem

# run init script and chkconfig it on
# chmod +x /etc/init.d/chef-client
# chkconfig chef-client on
# /etc/init.d/chef-client start
